
project_id = "qolsgxwlaevoavmnvqkf"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
webhook_enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[auth.email]
enabled = true

[analytics]
enabled = false
port = 54327

[experimental]
multi_schemas = false

[[functions]]
name = "check-subscription"
verify_jwt = true
system_features = ["scheduled"]

[[functions]]
name = "create-checkout"
verify_jwt = true
system_features = ["scheduled"]

[[functions]]
name = "customer-portal"
verify_jwt = true
system_features = ["scheduled"]
