// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qolsgxwlaevoavmnvqkf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvbHNneHdsYWV2b2F2bW52cWtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3OTg0NzUsImV4cCI6MjA2MzM3NDQ3NX0.7LZ6QP8fZbDNBWTLbOmtAX6JKFqUvdZolrGO5K4nQIA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);